### ISSUE TITLE
[RFC] Non required links

### ISSUE THREAD

**Issue by adrienbrault** [TheFootballSocialClub/FSCHateoasBundle#34]
Hey,

I see that many people are interested in non required relation.
An example would be a User that could have a manager, but not always.

The current PR try catch the parameters creation or the url generation. I dot not like this as this could hide an error (configuration, runtime, whatever).

What I propose:

```
@Relation("manager", @Route("user_get", parameters = {"id" = "manager.id"}), required_parameters = {"manager"})
```

Without the new `required_parameters` option, the behavior would stay the same.
`required_parameters` would accept an array of propertyPaths. If one of the propertyPath is null or false, then the relation link would not be created.

WDYT ?

**Comment by baldurrensch** [comment]
:+1:

**Comment by adrienbrault** [comment]
BTW, I'm not sure about the `required_parameters` name. If you have better ideas!

**Comment by stof** [comment]
The name looks weird. The parameter is not required in the relation. It is the condition to add the relation (and it is not even a parameter with the meaning of `parameters` in the annotation).

**Comment by marapper** [comment]
I don't think that catching of exception is something bad. But I like this idea. 

A little longer example:

Event has task (OneToOne), task has assignee (ManyToOne). Task could be empty and task could not have assignee. In any case we don't need relation. In that case we always should use

```
@Relation("assignee", @Route("user_get", parameters = {"id" = ".task.assignee.id"}), required_parameters = {"task", "assignee"})
```

But I really don't see situations when somebody will want to make task required and assignee not required. ORM Restrictions works good enough.

And if we have few relations it will be

```
@Relation("assignee", @Route("user_get", parameters = {"id" = ".task.assignee.id"}), required_parameters = {"task", "assignee"})
@Relation("assignor", @Route("user_get", parameters = {"id" = ".task.assignor.id"}), required_parameters = {"task", "assignor"})
@Relation("smth", @Route("smth_get", parameters = {"id" = ".task.smth.id"}), required_parameters = {"task", "smth"})
```

---

Second thing is backward compability. I think relations should be required by default.

---

And in fact it's condition of @Route, not @Relation. That's why name looks weird. I see two ways:

```
@Route("smth_get", parameters = {"id" = ".task.smth.id"}, nullable={"task"})
```

or just

```
@Route("smth_get", parameters = {"id" = ".?task.smth.id"})
```

In any case we can't use PropertyPath as usual and need duplicate its functionality.

@Relation with empty href will be hided always.

**Comment by baldurrensch** [comment]
What about instead of `nullable`, calling it `allow_null` or `allow_empty`?

**Comment by marapper** [comment]
:thumbsup:

And full path could be more reasonable.

For example:

```
@Route("smth_get", parameters = {"id" = ".task.smth.id"}, allow_empty={".task.smth"})
```

So we could use PropertyPath and it would work with any data types (0, "", null).

**Comment by adrienbrault** [comment]
I don't think that this should be part of the @Route configuration.

What about a `skip_if_null` / `ignore_if_null`  / `ignore_when_null` ?

**Comment by marapper** [comment]
As a proof of concept https://github.com/TheFootballSocialClub/FSCHateoasBundle/pull/36

The bundle uses symfony 2.2 already with displaced PropertyPath so I can't check is it correct.

I agree that in @Relation this feature is more useful. But maybe it should be skip_if_empty not only null? For example:

```
@Relation("rel", href="..." skip_if_empty=".task.active")
```

Should be skipped if `active` is 0/null/"". It could be very flexible.

And more sophisticated approach:

```
@Relation("rel", href="..." skip_if={".task.active" = 1})
```

**Comment by adrienbrault** [comment]
Closing as #42 is going to be merged
